export const copy={
  "ko": {
    "asOfNote": "선택한 날짜 당시의 보유 현황입니다.",
    "noComparison": "직전 분기 자료가 없어 보유 변화를 비교할 수 없습니다. 전체 보유 현황은 확인할 수 있습니다.",
    "noChanges": "직전 분기 대비 보유 수량 변화가 없습니다.",

    "allocation": "종목별 보유 비중",
    "allocationNote": "공시 평가금액 기준 · 주식·ETF 등 현물만 포함하며 옵션·채권·현금은 제외합니다. 모든 종목을 개별 표시합니다. 아래 검색과 관계없이 전체 현물 기준입니다.",
    "other": "기타",
    "reportedEquities": "공시 현물",
    "valuesMissing": "평가금액을 확인 중입니다. 금액이 모두 확인되면 비중을 표시합니다.",
    "noEquities": "차트에 표시할 현물 보유가 없습니다.",

    "viewReport": "보고서 보기",
    "backReports": "보고서 목록",
    "reportMissing": "보고서를 찾을 수 없습니다.",

    "allHoldings": "전체 보유",
    "holdingChanges": "보유 변화",
    "holdingsNote": "보유 기준일 당시 보유 현황이며 실시간 잔고가 아닙니다. 이 보고서의 전체 보유 내역을 표시합니다.",
    "quantityHeld": "보유 수량",
    "noHoldings": "보유 내역이 없습니다.",
    "debt": "채권 · 원금",
    "positionsShown": "표시 항목",

    "reports": "기관별 보고서",
    "reportHint": "보고서를 선택해 보유 변화와 전체 보유 현황을 확인하세요.",
    "reportCount": "표시된 보유 변화",
    "expand": "보유 변화 보기",
    "collapse": "접기",
    "filteredReports": "검색 조건에 맞는 보유 변화만 표시합니다.",

    "feed": "공시 피드",
    "refresh": "새로고침",
    "all": "전체",
    "search": "종목·회사명·CUSIP 검색",
    "allManagers": "모든 투자자",
    "allAssets": "모든 자산",
    "stock": "주식",
    "put": "풋옵션",
    "call": "콜옵션",
    "new": "신규 보유",
    "increased": "보유 증가",
    "reduced": "보유 감소",
    "closed": "보유 종료",
    "loading": "불러오는 중…",
    "empty": "표시할 공시가 없습니다.",
    "emptyHint": "검색 조건을 변경하거나 수집 상태를 확인하세요.",
    "error": "데이터를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.",
    "loadMore": "더 보기",
    "name": "투자자",
    "ticker": "종목 코드",
    "action": "보유 변화",
    "asset": "자산 유형",
    "allChanges": "모든 변동",
    "timing": "공시 공개 후의 보유 변화입니다. 13F는 통상 분기 말 이후 45일 이내 제출되며, 실제 거래일·가격은 확인되지 않습니다.",
    "interpretation": "풋옵션 보유가 곧 공매도라는 뜻은 아닙니다. 주식 분할·이관 등도 수량을 바꿀 수 있습니다.",
    "filingDate": "공시일",
    "period": "보유 기준일",
    "previous": "이전 보고",
    "current": "이번 보고",
    "unknownTrade": "실제 거래일·가격: 공시에서 확인 불가",
    "source": "공시 원문",
    "optionUnit": "기초자산 환산 수량이며 옵션 계약 수나 지출액이 아닙니다.",
    "shareUnit": "공시에 보고된 주식 수량",
    "principalUnit": "공시상 원금 단위",
    "review": "정정 확인 필요",
    "reviewNote": "관련 기간에 정정 공시가 있습니다. 정확한 보유 내역은 공시 원문을 확인해 주세요.",
    "status": "수집 상태",
    "lastSuccess": "마지막 성공",
    "pending": "첫 수집 대기",
    "ready": "수집 정상",
    "syncing": "수집 중",
    "failed": "수집 실패 · 다음 주기에 재시도",
    "noFilings": "최근 13F 없음",
    "never": "아직 없음",
    "stale": "26시간 이상 갱신되지 않음",
    "schedule": "매일 오전 7시부터 순차 수집 (한국시간)",
    "change": "수량 변화",
    "close": "닫기",
    "history": "첫 수집 자료",
    "institution": "인물 이름은 운용사를 찾기 위한 표시이며 개인 계좌나 현재 운용 참여 여부를 의미하지 않습니다.",
    "older": "공시가 새로 제출되지 않으면 이전 보유 기준일이 그대로 표시됩니다.",
    "investors": "투자자 목록"
  },
  "en": {
    "asOfNote": "Holdings as of the selected date.",
    "noComparison": "The preceding quarter is not available for comparison. You can still view all holdings.",
    "noChanges": "No quantity changes from the preceding quarter.",

    "allocation": "Holdings allocation",
    "allocationNote": "Based on reported values of equities and ETFs. Options, debt and cash are excluded. Every position is shown individually, unaffected by the search below.",
    "other": "Other",
    "reportedEquities": "Reported equities",
    "valuesMissing": "Reported values are not yet complete. Allocation will appear once all values are available.",
    "noEquities": "No equity holdings to chart.",

    "viewReport": "View report",
    "backReports": "All reports",
    "reportMissing": "Report not found.",

    "allHoldings": "All holdings",
    "holdingChanges": "Holding changes",
    "holdingsNote": "Holdings as of the report date, not a live portfolio. This page shows the entire filing.",
    "quantityHeld": "Quantity held",
    "noHoldings": "No holdings in this report.",
    "debt": "Debt · principal",
    "positionsShown": "Positions shown",

    "reports": "Institution reports",
    "reportHint": "Select a report to view holding changes or all reported holdings.",
    "reportCount": "Matching holding changes",
    "expand": "View holding changes",
    "collapse": "Collapse",
    "filteredReports": "Only holding changes matching your filters are shown.",

    "feed": "Filing feed",
    "refresh": "Refresh",
    "all": "All",
    "search": "Search ticker, issuer or CUSIP",
    "allManagers": "All investors",
    "allAssets": "All assets",
    "stock": "Stock",
    "put": "Put",
    "call": "Call",
    "new": "New holding",
    "increased": "Increased",
    "reduced": "Reduced",
    "closed": "Exited",
    "loading": "Loading…",
    "empty": "No filings to display.",
    "emptyHint": "Change your filters or check collection status.",
    "error": "Could not load data. Please try again shortly.",
    "loadMore": "Load more",
    "name": "Investor",
    "ticker": "Ticker",
    "action": "Holding change",
    "asset": "Asset type",
    "allChanges": "All changes",
    "timing": "Changes reflect published filings. Form 13F is generally due within 45 days of quarter end; trade dates and execution prices are unknown.",
    "interpretation": "A put holding does not prove a short sale. Splits and transfers can also change reported quantities.",
    "filingDate": "Filed",
    "period": "Holdings as of",
    "previous": "Previous report",
    "current": "Current report",
    "unknownTrade": "Trade date and execution price: not disclosed",
    "source": "Original filing",
    "optionUnit": "Underlying-equivalent quantity, not option contracts or premium paid.",
    "shareUnit": "Reported share quantity",
    "principalUnit": "Reported principal amount",
    "review": "Amendment review",
    "reviewNote": "A relevant report was amended. Review the original filing for the reported holdings.",
    "status": "Collection status",
    "lastSuccess": "Last successful check",
    "pending": "Awaiting first collection",
    "ready": "Up to date",
    "syncing": "Checking",
    "failed": "Check failed · retries next cycle",
    "noFilings": "No recent 13F",
    "never": "Not yet",
    "stale": "No update for over 26 hours",
    "schedule": "Daily from 07:00 KST, one institution at a time",
    "change": "Quantity change",
    "close": "Close",
    "history": "Initial history",
    "institution": "Person names identify reporting firms, not personal accounts or current involvement in management.",
    "older": "Report dates remain unchanged until a newer filing is published.",
    "investors": "Investors"
  },
  "ja": {
    "asOfNote": "選択した日付時点の保有状況です。",
    "noComparison": "前四半期の資料がないため比較できません。全保有銘柄は確認できます。",
    "noChanges": "前四半期から保有数量の変動はありません。",

    "allocation": "銘柄別保有比率",
    "allocationNote": "開示評価額に基づく株式・ETF等の現物の比率です。オプション・債券・現金は除外。すべての銘柄を個別に表示します。下の検索条件には影響されません。",
    "other": "その他",
    "reportedEquities": "開示現物",
    "valuesMissing": "評価額を確認中です。すべての金額が確認でき次第、比率を表示します。",
    "noEquities": "表示する現物保有がありません。",

    "viewReport": "レポートを見る",
    "backReports": "レポート一覧",
    "reportMissing": "レポートが見つかりません。",

    "allHoldings": "全保有銘柄",
    "holdingChanges": "保有変動",
    "holdingsNote": "保有基準日時点の保有状況です。リアルタイムの残高ではありません。この報告の全保有銘柄を表示します。",
    "quantityHeld": "保有数量",
    "noHoldings": "保有銘柄がありません。",
    "debt": "債券・元本",
    "positionsShown": "表示件数",

    "reports": "機関別レポート",
    "reportHint": "レポートを開くと銘柄ごとの保有変動を確認できます。",
    "reportCount": "該当する保有変動",
    "expand": "保有変動を見る",
    "collapse": "閉じる",
    "filteredReports": "検索条件に一致する保有変動のみ表示しています。",

    "feed": "開示フィード",
    "refresh": "更新",
    "all": "すべて",
    "search": "銘柄・企業名・CUSIPを検索",
    "allManagers": "すべての投資家",
    "allAssets": "すべての資産",
    "stock": "株式",
    "put": "プット",
    "call": "コール",
    "new": "新規保有",
    "increased": "保有増加",
    "reduced": "保有減少",
    "closed": "保有終了",
    "loading": "読込中…",
    "empty": "表示する開示がありません。",
    "emptyHint": "検索条件や収集状況を確認してください。",
    "error": "データを取得できませんでした。時間をおいて再試行してください。",
    "loadMore": "もっと見る",
    "name": "投資家",
    "ticker": "銘柄コード",
    "action": "保有変動",
    "asset": "資産の種類",
    "allChanges": "すべての変動",
    "timing": "公開後の保有変動です。13Fは通常四半期末から45日以内に提出され、実際の取引日・価格は不明です。",
    "interpretation": "プット保有は空売りの証明ではありません。株式分割や移管でも数量が変わります。",
    "filingDate": "提出日",
    "period": "保有基準日",
    "previous": "前回報告",
    "current": "今回報告",
    "unknownTrade": "実際の取引日・価格：開示から確認不可",
    "source": "開示原文",
    "optionUnit": "原資産換算数量であり、契約数や支払額ではありません。",
    "shareUnit": "報告された株数",
    "principalUnit": "報告された元本額",
    "review": "訂正の確認が必要",
    "reviewNote": "関連期間に訂正開示があります。正確な保有内容は開示原文を確認してください。",
    "status": "収集状況",
    "lastSuccess": "最終成功",
    "pending": "初回収集待ち",
    "ready": "収集正常",
    "syncing": "確認中",
    "failed": "収集失敗・次回再試行",
    "noFilings": "最近の13Fなし",
    "never": "まだありません",
    "stale": "26時間以上更新なし",
    "schedule": "毎日午前7時から順次収集（韓国時間）",
    "change": "数量の変化",
    "close": "閉じる",
    "history": "初回収集履歴",
    "institution": "個人名は報告機関の識別用です。個人口座や現在の運用参加を示すものではありません。",
    "older": "新しい開示が提出されるまで保有基準日は変わりません。",
    "investors": "投資家一覧"
  }
};
